exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('podcasts').del()
    .then(function() {
      // Inserts seed entries
      return knex('podcasts').insert([{
          email: 'kill@tony.com',
          hashed_password: '1234',
          name: "Kill Tony",
          itunes_url: "https://itunes.apple.com/us/podcast/kill-tony/id1042361179?mt=2",
          play_url: "https://itunes.apple.com/us/podcast/kill-tony/id1042361179?mt=2",
          website: "http://www.deathsquad.tv/category/kill-tony/",
          reader: 'Tony Hinchcliffe',
          summary: "The weekly live show recorded at the world famous Comedy Store with your hosts Tony Hinchcliffe and Brian Redban.",
          demo: '20 - 40 males and females.',
          subject: 'Comedy',
          profile_image: 'http://is1.mzstatic.com/image/thumb/Music62/v4/a2/28/46/a22846be-aa37-a34f-b0b1-82f2eda98fff/source/1200x630bb.jpg',
          images: '',
          contact: 'mailto:jakem@avalon-usa.com',
          tags: 'comedian, Tony Hinchcliffe, live, comedy store, Redban, funny',
          loginType: 'podcaster'
        },
        {
          email: 'jre@jre.com',
          hashed_password: '1234',
          name: 'The Joe Rogan Experience',
          itunes_url: 'https://itunes.apple.com/us/podcast/the-joe-rogan-experience/id360084272?mt=2',
          play_url: "https://itunes.apple.com/us/podcast/kill-tony/id1042361179?mt=2",
          website: 'http://podcasts.joerogan.net/',
          reader: 'Joe Rogan',
          summary: "The Joe Rogan Experience podcast is a long form conversation hosted by comedian, UFC color commentator, and actor Joe Rogan with friends and guests that have included comedians, actors, musicians, MMA instructors and commentators, authors, and artists. The Joe Rogan Experience was voted the Best Comedy Podcast of 2012 on iTunes. In addition online listening, fans can watch a videocast of the show live on Ustream or tune in on Sirius XM’s “The Virus” channel on Saturdays at Noon ET and Sundays at 5:00 AM and 6:00 PM ET.",
          demo: '25 - 40 males',
          subject: 'Talk',
          profile_image: "http://is4.mzstatic.com/image/thumb/Music127/v4/d0/e6/5f/d0e65f81-c2cf-7f59-38e4-6abcfab7e38a/source/1200x630bb.jpg",
          images: '',
          contact: 'mailto:jresponsorship@joerogan.net',
          tags: 'joe rogan, comedy',
          loginType: 'podcaster'
        },
        {
          email: 'atlanta@monster.com',
          hashed_password: '1234',
          name: 'Atlanta Monster',
          itunes_url: 'https://itunes.apple.com/us/podcast/atlanta-monster/id1324249769?mt=2',
          play_url: "https://itunes.apple.com/us/podcast/kill-tony/id1042361179?mt=2",
          website: 'https://atlantamonster.com',
          reader: 'Payne Lindsey',
          summary: "From the producers of Up and Vanished, Tenderfoot TV and HowStuffWorks present, ‘Atlanta Monster.’ This true crime podcast tells the story of one of the city’s darkest secrets, The Atlanta Child Murders. Nearly 40 years after these horrific crimes, many questions still remain. Host Payne Lindsey aims to find truth and provide closure, reexamining the disappearance and murder of over 25 African American children and young adults.",
          demo: '25 - 40 males and females',
          subject: 'Society and Culture',
          profile_image: "http://is2.mzstatic.com/image/thumb/Music128/v4/0a/a9/af/0aa9af1b-cfe8-5867-71c6-041f47feb99e/source/1200x630bb.jpg",
          images: '',
          contact: 'https://atlantamonster.com/contact/',
          tags: 'Atlanta, HowStuffWorks, Up and Vanished',
          loginType: 'podcaster'
        },
        {
          email: 'PKA@PKA.com',
          hashed_password: '1234',
          name: 'PKA',
          itunes_url: 'https://itunes.apple.com/us/podcast/painkiller-already/id369968602?mt=2',
          play_url: 'https://itunes.apple.com/us/podcast/painkiller-already/id369968602?mt=2',
          website: 'https://painkilleralready.podbean.com/',
          reader: 'WoodysGamertag',
          summary: "Painkiller Already, LLC is a weekly podcast featuring hosts: WoodysGamertag, FPS Kyle and Murka. Commonly referred to as PKA, the podcast has been steam-rolling through the airwaves since early 2010. PKA discusses current events, news, relives comedic stories and gives their perspective on life while throwing in their comedic twist to all discussions.",
          demo: "15 - 35 males",
          subject: 'Comedy',
          profile_image: "http://is3.mzstatic.com/image/thumb/Music/v4/f1/17/61/f11761b7-232c-4358-8094-0640fb34fde8/source/1200x630bb.jpg",
          images: '',
          contact: 'mailto:business@pkaonline.com',
          tags: 'video games, comedy, WoodysGamertag, FPS Kyle, Call of Duty',
          loginType: 'podcaster'
        },
        {
          email: 'bill@burr.com',
          hashed_password: '1234',
          name: 'Monday Morning Podcast',
          itunes_url: 'https://itunes.apple.com/us/podcast/painkiller-already/id369968602?mt=2',
          play_url: 'https://itunes.apple.com/us/podcast/painkiller-already/id369968602?mt=2',
          website: 'https://painkilleralready.podbean.com/',
          reader: 'Bill Burr',
          summary: "Bill Burr rants about relationship advice, sports and the Illuminati.",
          demo: "21 - 35 males",
          subject: 'Comedy',
          profile_image: "http://is2.mzstatic.com/image/thumb/Music71/v4/ec/3f/92/ec3f924d-e918-086c-777e-cc64e1237984/source/1200x630bb.jpg",
          images: '',
          contact: 'mailto:MBerkowitz@wmeentertainment.com',
          tags: 'comedy, sports, relationships',
          loginType: 'podcaster'
        },
        {
          email: 'the@nerdist.com',
          hashed_password: '1234',
          name: 'The Nerdist',
          itunes_url: 'https://itunes.apple.com/us/podcast/the-nerdist/id355187485?mt=2',
          play_url: 'https://itunes.apple.com/us/podcast/the-nerdist/id355187485?mt=2',
          website: 'https://nerdist.com/',
          reader: 'Chris Hardwick',
          summary: "I am Chris Hardwick. I am on TV a lot and have a blog at nerdist.com. This podcast is basically just me talking about stuff and things with my two nerdy friends Jonah Ray and Matt Mira, and usually someone more famous than all of us. Occasionally we swear because that is fun. I hope you like it, but if you don't I'm sure you will not hesitate to unfurl your rage in the 'reviews' section because that's how the Internet works.",
          demo: "21 - 35 males and females",
          subject: 'Comedy',
          profile_image: "http://is5.mzstatic.com/image/thumb/Music71/v4/08/68/01/0868010d-eba5-10ca-250e-d32354de5180/source/1200x630bb.jpg",
          images: '',
          contact: 'mailto:advertising@nerdist.com',
          tags: 'Comic Books, Movies, Video Games, TV',
          loginType: 'podcaster'
        },
        {
          email: 'Dinner@Party.xom',
          hashed_password: '1234',
          name: 'Dinner Party',
          itunes_url: 'https://itunes.apple.com/us/podcast/the-dinner-party-download/id289105827?mt=2',
          play_url: 'https://itunes.apple.com/us/podcast/the-dinner-party-download/id289105827?mt=2',
          website: 'https://www.dinnerpartydownload.org/podcast/',
          reader: 'Rico Gagliano',
          summary: "Welcome to The Dinner Party Download, a fast and funny hour of culture, food, and conversation. Think of it as public radio’s arts & leisure section. In every episode, you’ll learn a joke… bone up on an odd bit of history and then wash it down with a themed cocktail recipe… meet artists of note (Pharrell Williams, Scarlett Johansson, and Steve Martin to name a few)… have your burning etiquette questions answered by the likes of Mel Brooks or Aisha Tyler… savor an emerging food trend and hear your new favorite song. Plus, unconventional wisdom from hosts Rico Gagliano and Brendan Francis Newnam.",
          demo: '40 - 70 males and females',
          subject: 'Society and Culture',
          profile_image: "http://is5.mzstatic.com/image/thumb/Music111/v4/d7/27/b1/d727b1a1-28f0-9f9f-dbcb-443ca5c0c188/source/1200x630bb.jpg",
          images: '',
          contact: 'https://www.dinnerpartydownload.org/podcast/',
          tags: 'Atlanta, HowStuffWorks, Up and Vanished',
          loginType: 'podcaster'
        },
        {
          email: 'star@talk.com',
          hashed_password: '1234',
          name: 'Star Talk',
          itunes_url: "https://itunes.apple.com/us/podcast/startalk-radio/id325404506?mt=2",
          play_url: "https://itunes.apple.com/us/podcast/startalk-radio/id325404506?mt=2",
          website: "https://www.startalkradio.net/",
          reader: 'Neil deGrasse Tyson',
          summary: "StarTalk is a podcast on space, science, and popular culture hosted by astrophysicist Neil deGrasse Tyson, with various comic and celebrity co-hosts and frequent guests from the worlds of science and entertainment.",
          demo: "30 - 40 males and females.",
          subject: 'Science',
          profile_image: "http://is2.mzstatic.com/image/thumb/Music62/v4/8e/0a/70/8e0a7014-9ccc-b532-5eb7-2b803d1a571a/source/1200x630bb.jpg",
          images: '',
          contact: 'mailto:advertising@startalkradio.net',
          tags: 'science, space, neil degreasse tyson',
          loginType: 'podcaster'
        },
        {
          email: 'the@moth.com',
          hashed_password: '1234',
          name: 'The Moth',
          itunes_url: "https://itunes.apple.com/us/podcast/the-moth/id275699983?mt=2",
          play_url: "https://itunes.apple.com/us/podcast/the-moth/id275699983?mt=2",
          website: "https://themoth.org/podcast",
          reader: 'Dan Kennedy',
          summary: "The Moth is true stories, told live and without notes. The Moth celebrates the ability of stories to honor both the diversity and commonality of human experience, and to satisfy a vital human need for connection. It seeks to present recognized storytellers among established and emerging writers, performers and artists and to encourage storytelling among communities whose stories often go unheard.",
          demo: "16 - 60 males and females.",
          subject: 'Preforming Arts',
          profile_image: "http://is2.mzstatic.com/image/thumb/Music62/v4/e4/21/0e/e4210e1b-9efc-3064-d878-da592b8a92c8/source/1200x630bb.jpg",
          images: '',
          contact: '(212) 742-0551',
          tags: 'talk, live, stories, NPR, storytelling',
          loginType: 'podcaster'
        },
        {
          email: 's@town.com',
          hashed_password: '1234',
          name: 'S Town',
          itunes_url: "https://itunes.apple.com/us/podcast/s-town/id1212558767?mt=2",
          play_url: "https://itunes.apple.com/us/podcast/s-town/id1212558767?mt=2",
          website: "https://stownpodcast.org/",
          reader: 'Brian Reed',
          summary: "S-Town is a new podcast from Serial and This American Life, hosted by Brian Reed, about a man named John who despises his Alabama town and decides to do something about it. He asks Brian to investigate the son of a wealthy family who’s allegedly been bragging that he got away with murder. But then someone else ends up dead, and the search for the truth leads to a nasty feud, a hunt for hidden treasure, and an unearthing of the mysteries of one man’s life.",
          demo: "30 - 40 males and females.",
          subject: 'Personal Journal',
          profile_image: "http://is3.mzstatic.com/image/thumb/Music111/v4/e3/6f/f6/e36ff694-9e7d-c46e-7687-3856749d670f/source/1200x630bb.jpg",
          images: '',
          contact: 'mailto:press@stownpodcast.org',
          tags: 'personal Journal, clock, NPR, this american life',
          loginType: 'podcaster'
        },
        {
          email: 'the@vergecast.com',
          hashed_password: '1234',
          name: 'The Vergecast',
          itunes_url: "https://itunes.apple.com/us/podcast/the-vergecast/id430333725?mt=2",
          play_url: "https://itunes.apple.com/us/podcast/the-vergecast/id430333725?mt=2",
          website: "https://art19.com/shows/vergecast",
          reader: 'Nilay Patel',
          summary: "The Vergecast is your source for an irreverent and informative look at what's happening right now (and next) in the world of technology and gadgets. Hosted by Nilay Patel and Dieter Bohn, alongside a cavalcade of tech luminaries, Vergecast is the only podcast you need to make sense of the week in tech news. And your life.",
          demo: "30 - 40 tech enthusiasts",
          subject: 'Technology',
          profile_image: "http://is5.mzstatic.com/image/thumb/Music19/v4/b5/f3/1e/b5f31eaa-a3d3-2c30-377f-cc74713cc07b/source/1200x630bb.jpg",
          images: '',
          contact: 'https://www.theverge.com/contact-the-verge',
          tags: 'science, technology, tech, apple, samsung',
          loginType: 'podcaster'
        },
      ]);
    });
};
